import type Database from "better-sqlite3";

export interface LinkedInTargetAccountState {
  account_id: string;
  target_id: string;
  unipile_provider_id: string | null;
  unipile_chat_id: string | null;
  degree: number | null;
  connection_requested_at: string | null;
  connected_at: string | null;
  message_sent_at: string | null;
}

interface LegacyTargetState {
  id: string;
  unipile_provider_id?: string | null;
  unipile_chat_id?: string | null;
  degree?: number | null;
  connection_requested_at?: string | null;
  connected_at?: string | null;
  message_sent_at?: string | null;
  last_replied_account_id?: string | null;
}

/**
 * Picks the thread to use for outbound. Prefers the thread with the most history:
 * ordering by recency alone can pick a throwaway one-message thread over the real
 * conversation.
 */
function pickBestThreadId(db: Database.Database, accountId: string, targetId: string): string | null {
  const rows = db.prepare(`
    SELECT external_thread_id AS threadId, COUNT(*) AS total, MAX(datetime(sent_at)) AS lastAt
    FROM linkedin_inbox_messages
    WHERE account_id = ? AND target_id = ?
      AND external_thread_id IS NOT NULL AND external_thread_id != ''
      AND external_thread_id NOT LIKE 'urn:li:%' AND external_thread_id NOT LIKE 'thread%'
    GROUP BY external_thread_id
    ORDER BY total DESC, lastAt DESC
    LIMIT 1
  `).get(accountId, targetId) as { threadId?: string } | undefined;
  return rows?.threadId || null;
}

/**
 * Unipile chat ids are opaque provider ids (e.g. `LZjiQ7R5WGS...`). Historically this
 * column was seeded with LinkedIn URN placeholders such as
 * `urn:li:msg_conversation:(test_more)`, which are not usable as chat ids and make
 * every outbound send fail with 404. Treat those as "no chat yet".
 */
export function isUsableUnipileChatId(value: string | null | undefined): boolean {
  const chatId = String(value || "").trim();
  if (!chatId) return false;
  if (/^urn:li:/i.test(chatId)) return false;
  // `thread-<uuid>` is the synthetic fallback generated by reply-linkedin; `thread_<slug>`
  // is seeded demo data. Neither is a real Unipile chat id.
  if (/^thread[-_]/i.test(chatId)) return false;
  return true;
}

/**
 * Returns account-scoped LinkedIn state, creating a compatibility projection for
 * older single-account installations when needed.
 */
export function ensureLinkedInTargetAccountState(
  db: Database.Database,
  accountId: string,
  target: LegacyTargetState,
): LinkedInTargetAccountState {
  const existing = db.prepare(`
    SELECT account_id, target_id, unipile_provider_id, unipile_chat_id, degree,
      connection_requested_at, connected_at, message_sent_at
    FROM linkedin_target_accounts WHERE account_id = ? AND target_id = ?
  `).get(accountId, target.id) as LinkedInTargetAccountState | undefined;
  if (existing) {
    // Never hand back an unusable chat id: fall back to a real thread seen for this
    // account+target, otherwise to the legacy target column.
    if (isUsableUnipileChatId(existing.unipile_chat_id)) return existing;
    const recovered = pickBestThreadId(db, accountId, target.id)
      || (isUsableUnipileChatId(target.unipile_chat_id) ? target.unipile_chat_id : null);
    if (recovered) {
      db.prepare(`
        UPDATE linkedin_target_accounts SET unipile_chat_id = ?, updated_at = datetime('now')
        WHERE account_id = ? AND target_id = ?
      `).run(recovered, accountId, target.id);
      return { ...existing, unipile_chat_id: recovered };
    }
    return { ...existing, unipile_chat_id: null };
  }

  const accountCount = (db.prepare("SELECT COUNT(*) AS count FROM accounts").get() as { count: number }).count;
  const mayInheritRelationship = accountCount <= 1 || target.last_replied_account_id === accountId;
  const inheritedChatId = mayInheritRelationship ? target.unipile_chat_id || null : null;
  const state: LinkedInTargetAccountState = {
    account_id: accountId,
    target_id: target.id,
    unipile_provider_id: target.unipile_provider_id || null,
    unipile_chat_id: pickBestThreadId(db, accountId, target.id)
      || (isUsableUnipileChatId(inheritedChatId) ? inheritedChatId : null),
    degree: mayInheritRelationship ? target.degree ?? null : null,
    connection_requested_at: mayInheritRelationship ? target.connection_requested_at || null : null,
    connected_at: mayInheritRelationship ? target.connected_at || null : null,
    message_sent_at: mayInheritRelationship ? target.message_sent_at || null : null,
  };
  db.prepare(`
    INSERT INTO linkedin_target_accounts (
      account_id, target_id, unipile_provider_id, unipile_chat_id, degree,
      connection_requested_at, connected_at, message_sent_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(account_id, target_id) DO NOTHING
  `).run(
    state.account_id,
    state.target_id,
    state.unipile_provider_id,
    state.unipile_chat_id,
    state.degree,
    state.connection_requested_at,
    state.connected_at,
    state.message_sent_at,
  );
  return db.prepare(`
    SELECT account_id, target_id, unipile_provider_id, unipile_chat_id, degree,
      connection_requested_at, connected_at, message_sent_at
    FROM linkedin_target_accounts WHERE account_id = ? AND target_id = ?
  `).get(accountId, target.id) as LinkedInTargetAccountState;
}

export function updateLinkedInTargetAccountState(
  db: Database.Database,
  accountId: string,
  targetId: string,
  updates: Partial<Omit<LinkedInTargetAccountState, "account_id" | "target_id">>,
): void {
  const allowed = [
    "unipile_provider_id",
    "unipile_chat_id",
    "degree",
    "connection_requested_at",
    "connected_at",
    "message_sent_at",
  ] as const;
  const entries = allowed.filter((field) => Object.prototype.hasOwnProperty.call(updates, field));
  if (entries.length === 0) return;
  db.prepare(`
    INSERT INTO linkedin_target_accounts (account_id, target_id)
    VALUES (?, ?)
    ON CONFLICT(account_id, target_id) DO NOTHING
  `).run(accountId, targetId);
  const setClause = entries.map((field) => `${field} = ?`).join(", ");
  const values = entries.map((field) => updates[field]);
  db.prepare(`
    UPDATE linkedin_target_accounts
    SET ${setClause}, updated_at = datetime('now')
    WHERE account_id = ? AND target_id = ?
  `).run(...values, accountId, targetId);
}

export function projectLinkedInTargetState(
  db: Database.Database,
  targetId: string,
  updates: Partial<Omit<LinkedInTargetAccountState, "account_id" | "target_id">>,
): void {
  const allowed = [
    "unipile_provider_id",
    "unipile_chat_id",
    "degree",
    "connection_requested_at",
    "connected_at",
    "message_sent_at",
  ] as const;
  const entries = allowed.filter((field) => Object.prototype.hasOwnProperty.call(updates, field));
  if (entries.length === 0) return;
  const setClause = entries.map((field) => `${field} = ?`).join(", ");
  const values = entries.map((field) => updates[field]);
  db.prepare(`UPDATE targets SET ${setClause} WHERE id = ?`).run(...values, targetId);
}

export function markLinkedInTargetState(
  db: Database.Database,
  accountId: string,
  targetId: string,
  updates: Partial<Omit<LinkedInTargetAccountState, "account_id" | "target_id">>,
): void {
  updateLinkedInTargetAccountState(db, accountId, targetId, updates);
  projectLinkedInTargetState(db, targetId, updates);
}
